In [1]:
import pandas as pd
import numpy as np

In [2]:
drop_cols = ['OID_', 'SOURCE_ID', 'IS_SEED']
all_june_20 = pd.read_csv("../Datasets/Clusters/3_cluster_spatial/all_june_20_3c.csv").drop(columns=drop_cols)
all_july_20 = pd.read_csv("../Datasets/Clusters/3_cluster_spatial/all_july_20_3c.csv").drop(columns=drop_cols)

all_june_21 = pd.read_csv("../Datasets/Clusters/3_cluster_spatial/all_june_21_3c.csv").drop(columns=drop_cols)
all_july_21 = pd.read_csv("../Datasets/Clusters/3_cluster_spatial/all_july_21_3c.csv").drop(columns=drop_cols)

all_june_22 = pd.read_csv("../Datasets/Clusters/3_cluster_spatial/all_june_22_3c.csv").drop(columns=drop_cols)
all_july_22 = pd.read_csv("../Datasets/Clusters/3_cluster_spatial/all_july_22_3c.csv").drop(columns=drop_cols)

In [3]:
def ClusterCorrelation(df1, df2):
    correlations = []
    n_clusters = len(np.unique(df1['CLUSTER_ID']))
    features = [col for col in df1.columns if col != 'CLUSTER_ID']
    for i in range(1, n_clusters + 1):
        corr_df1 = df1[df1['CLUSTER_ID'] == i].reset_index(drop='True')
        for j in range(1, n_clusters + 1):
            corr_df2 = df2[df2['CLUSTER_ID'] == j].reset_index(drop='True')
            correlations.append(np.average(corr_df1[features].corrwith(corr_df2[features]).values))

    return correlations

### Correlation between June 2020, June 2021, and June 2022

In [4]:
cols = ['2021 Cluster ' + str(i) for i in range(1,4)] + ['2022 Cluster ' + str(i) for i in range(1,4)]
df = pd.DataFrame(columns=['2020 Cluster'] + cols)
corr_2020_2021 = ClusterCorrelation(all_june_20, all_june_21)
corr_2020_2022 = ClusterCorrelation(all_june_20, all_june_22)
df.loc[len(df)] = ['1'] + corr_2020_2021[:3] + corr_2020_2022[:3]
df.loc[len(df)] = ['2'] + corr_2020_2021[3:6] + corr_2020_2022[3:6]
df.loc[len(df)] = ['3'] + corr_2020_2021[6:9] + corr_2020_2022[6:9]
df.set_index("2020 Cluster", inplace=True)
df

,2021 Cluster 1,2021 Cluster 2,2021 Cluster 3,2022 Cluster 1,2022 Cluster 2,2022 Cluster 3
2020 Cluster,,,,,,
1,-0.042131,0.214215,0.028376,0.066563,0.014247,-0.012725
2,-0.012634,0.279890,-0.014573,0.054856,-0.031769,-0.050792
3,0.058478,-0.102005,0.111094,0.139377,-0.082807,-0.068159

### Correlation between June 2021 and June 2022

In [5]:
cols = ['2022 Cluster ' + str(i) for i in range(1,4)]
df = pd.DataFrame(columns=['2021 Cluster'] + cols)
corr_2021_2022 = ClusterCorrelation(all_june_21, all_june_22)
df.loc[len(df)] = ['1'] + corr_2021_2022[:3]
df.loc[len(df)] = ['2'] + corr_2021_2022[3:6]
df.loc[len(df)] = ['3'] + corr_2021_2022[6:9]
df.set_index("2021 Cluster", inplace=True)
df

              2022 Cluster 1  2022 Cluster 2  2022 Cluster 3
2021 Cluster
1                   0.086850       -0.122167       -0.020478
2                  -0.083093       -0.036000        0.009425
3                   0.206728        0.177844        0.019288

### Correlation between July 2020, July 2021, and July 2022

In [6]:
cols = ['2021 Cluster ' + str(i) for i in range(1,4)] + ['2022 Cluster ' + str(i) for i in range(1,4)]
df = pd.DataFrame(columns=['2020 Cluster'] + cols)
corr_2020_2021 = ClusterCorrelation(all_july_20, all_july_21)
corr_2020_2022 = ClusterCorrelation(all_july_20, all_july_22)
df.loc[len(df)] = ['1'] + corr_2020_2021[:3] + corr_2020_2022[:3]
df.loc[len(df)] = ['2'] + corr_2020_2021[3:6] + corr_2020_2022[3:6]
df.loc[len(df)] = ['3'] + corr_2020_2021[6:9] + corr_2020_2022[6:9]
df.set_index("2020 Cluster", inplace=True)
df

,2021 Cluster 1,2021 Cluster 2,2021 Cluster 3,2022 Cluster 1,2022 Cluster 2,2022 Cluster 3
2020 Cluster,,,,,,
1,0.164935,-0.106391,0.077818,0.151023,-0.045503,0.086983
2,-0.014160,-0.005274,-0.002751,0.030033,-0.152755,-0.051410
3,-0.025281,0.036533,-0.003026,-0.048382,-0.284084,-0.045220

### Correlation between July 2021 and July 2022

In [7]:
cols = ['2022 Cluster ' + str(i) for i in range(1,4)]
df = pd.DataFrame(columns=['2021 Cluster'] + cols)
corr_2021_2022 = ClusterCorrelation(all_july_21, all_july_22)
df.loc[len(df)] = ['1'] + corr_2021_2022[:3]
df.loc[len(df)] = ['2'] + corr_2021_2022[3:6]
df.loc[len(df)] = ['3'] + corr_2021_2022[6:9]
df.set_index("2021 Cluster", inplace=True)
df

              2022 Cluster 1  2022 Cluster 2  2022 Cluster 3
2021 Cluster
1                   0.066405       -0.052344        0.040302
2                   0.050602        0.028490       -0.061613
3                   0.071408       -0.019912        0.051706